version: 1
accounts:
  - name: central-bank
    coins: ["1000000000000token", "100000000stake"]
  - name: hana-bank
    coins: ["200000000000token", "100000000stake"]
validator:
  name: central-bank
  staked: "100000000stake"
  name: hana-bank
  staked: "100000000stake"