version: 1
accounts:
  - name: central-bank
    coins: ["1000000000000token", "100000000stake"]
  - name: hana-bank
    coins: ["200000000000token", "100000000stake"]
  - name: escrow
    coins: ["1000000000token"]
  - name: user1
    coins: ["500000000token"]
  - name: user2
    coins: ["200000000token"]
  - name: affiliate
    coins: ["300000000token"]
validator:
  name: central-bank
  staked: "100000000stake"
  name: hana-bank
  staked: "100000000stake"